# A sample Gemfile
source "https://rubygems.org"

# gem "rails"
gem 'sinatra'
gem 'omniauth-facebook'
gem 'data_mapper'
gem 'dm-mysql-adapter'
gem 'omniauth'
gem 'omniauth-identity'
gem 'savon', '~> 2.0'
gem 'mail'
